/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "surface-container-high": "#222a3d",
        "tertiary-fixed": "#ffddb8",
        "primary-fixed-dim": "#adc6ff",
        "on-secondary-fixed-variant": "#005236",
        "tertiary-fixed-dim": "#ffb95f",
        "on-tertiary-fixed-variant": "#653e00",
        "on-secondary-container": "#00311f",
        "primary-container": "#4d8eff",
        "on-background": "#dae2fd",
        "on-tertiary-container": "#3e2400",
        "secondary": "#4edea3",
        "on-secondary": "#003824",
        "surface-bright": "#31394d",
        "outline": "#8c909f",
        "secondary-container": "#00a572",
        "inverse-primary": "#005ac2",
        "error-container": "#93000a",
        "surface-tint": "#adc6ff",
        "surface-container-highest": "#2d3449",
        "primary": "#adc6ff",
        "surface-container-lowest": "#060e20",
        "error": "#ffb4ab",
        "on-surface": "#dae2fd",
        "surface-container": "#171f33",
        "secondary-fixed": "#6ffbbe",
        "on-tertiary": "#472a00",
        "inverse-surface": "#dae2fd",
        "surface-variant": "#2d3449",
        "primary-fixed": "#d8e2ff",
        "on-error": "#690005",
        "on-tertiary-fixed": "#2a1700",
        "secondary-fixed-dim": "#4edea3",
        "tertiary": "#ffb95f",
        "on-secondary-fixed": "#002113",
        "background": "#0b1326",
        "on-primary-container": "#00285d",
        "on-primary": "#002e6a",
        "inverse-on-surface": "#283044",
        "tertiary-container": "#ca8100",
        "surface-dim": "#0b1326",
        "surface-container-low": "#131b2e",
        "on-primary-fixed": "#001a42",
        "on-error-container": "#ffdad6",
        "surface": "#0b1326",
        "on-primary-fixed-variant": "#004395",
        "on-surface-variant": "#c2c6d6",
        "outline-variant": "#424754"
      },
      "spacing": {
        "xl": "48px",
        "sm": "16px",
        "lg": "32px",
        "base": "4px",
        "container-max": "1440px",
        "sidebar-width": "280px",
        "md": "24px",
        "xs": "8px"
      },
      "fontFamily": {
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "display-lg": ["Hanken Grotesk", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "title-lg": ["Hanken Grotesk", "sans-serif"]
      }
    },
  },
  plugins: [require('@tailwindcss/typography')],
}
